<%@ page import="gov.nysenate.sage.util.Resource" %>
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.js"></script>
    <script src="OpenLayers.js"></script>
    <script src="http://maps.google.com/maps/api/js?v=3.2&sensor=false"></script>
    <script>
    
    $(document).ready(function(){
        var map = new OpenLayers.Map({
            div: 'map',
        });
        
        // This is the layer that will hold the senate district features
        vectorLayer = new OpenLayers.Layer.Vector(
            "District Boundary",
            {
                strategies: [new OpenLayers.Strategy.Fixed()],
                
                // Load the matching features from geoserver
                protocol: new OpenLayers.Protocol.WFS({
                    version: "1.1.0",
                    url: "<%=Resource.get("geoserver.url")%>/wfs",
                    featurePrefix: 'nysenate', //geoserver worspace name
                    featureType: "senate", //geoserver Layer Name
                    geometryName: "geometry", // field in Feature Type details with type "Geometry"
                    filter: new OpenLayers.Filter.Comparison({
                        type: OpenLayers.Filter.Comparison.EQUAL_TO,
                        property: "DISTRICT",
                        value: "<%=request.getParameter("sd")%>",
                    }),
                }),
                
                // Compute the appropriate center point and zoom based on the previously loaded feature
                // TODO: Loop over all loaded features instead!
                onFeatureInsert: function(feature) {
                    var extent = feature.geometry.getBounds().clone();
                    var center = feature.geometry.bounds.getCenterLonLat();
                    feature.layer.map.setCenter(center);
                    feature.layer.map.zoomToExtent(extent);
                }
            }
        );
        // Bubble events up, why?
        vectorLayer.events.fallThrough = true;
        
        // Google's maps seem a lot better here. Not terribly surprising, we can still use OSM though
        // map.addLayer(new OpenLayers.Layer.OSM('map'));
        map.addLayer(new OpenLayers.Layer.Google("Google Streets", {numZoomLevels: 20}));
        map.addLayer(vectorLayer);
        
        <% if(request.getParameter("nonav") != null) { %>
            map.removeControl(map.getControl('OpenLayers.Control.Navigation_4'));
            map.removeControl(map.getControl('OpenLayers.Control.ArgParser_6'));
            map.removeControl(map.getControl('OpenLayers.Control.PanZoom_5'));
            map.removeControl(map.getControl('OpenLayers.Control.Attribution_7'));
            
        <% } else { %>
            // No Nav also means no markers
            markers = new OpenLayers.Layer.Markers("Markers");
            
            // Load the NYSenate.govJSON pre-generated by the ApiController.
            $.getJSON("json/sd<%=request.getParameter("sd")%>.json",function(json){
                for(var i in json.senate.senator.offices) {
                    var office = json.senate.senator.offices[i];
                    
                    // Project the office into the map projection
                    officeLocation = new OpenLayers.LonLat(office.lat, office.lon).transform(
                        new OpenLayers.Projection("EPSG:4326"),
                        map.getProjectionObject()
                    );

                    // And create a new OSM Marker on the map!
                    var officeMarker = new OpenLayers.Marker(officeLocation);
                    officeMarker.office = office;
                    markers.addMarker(officeMarker);             
                    officeMarker.events.register('mousedown',officeMarker, function(event) {
                        hasCloseBox = true;
                        anchorObject = null;
                        
                        var my_popup = this.popup;
                        // Attach the pop-up to the trigger for later retrieval
                        if (my_popup == null) {
                            my_popup = new OpenLayers.Popup.FramedCloud(
                                "Office Data",
                                event.object.lonlat,
                                new OpenLayers.Size(200,00),
                                office.officeName + "<br>" + office.street + "<br>" + office.city + ", " + office.state + "<br>Phone: " +office.phone + "<br>Fax: " + office.fax,
                                anchorObject, hasCloseBox,
                                function() {
                                    my_popup.toggle();
                                }
                            );
                            map.addPopup(my_popup);
                            my_popup.show();
                            this.popup = my_popup;
                        } else {
                            my_popup.toggle();
                        }
                        
                        OpenLayers.Event.stop(event);
                    });
                }
            });
            
            // markers hide under the kml layer otherwise
            markers.setZIndex(vectorLayer.getZIndex());
            map.addLayer(markers);
        <% } %>
    });

    </script>
</head>
<body>
    <div style="width:<%=request.getParameter("x")%>px; height:<%=request.getParameter("y")%>px;" id="map"></div>
</body>
</html>