source 'http://rubygems.org'

gem 'rails', '3.0.3'

gem 'Text', '1.1.2'

gem 'fastercsv', '1.5.4'

gem 'levenshtein', '0.2.0'

gem 'json', '1.5.1'

gem 'GeoRuby', '1.3.4'

gem 'Geocoder-US', '2.0.0', :path => '/home/ubuntu/ruby/geocoder'

#gem 'bleak_house', '7.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'sqlite3-ruby', :git => 'git://github.com/schuyler/sqlite3-ruby.git'

#gem 'sqlite3-ruby', :require => 'sqlite3'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
