#!/bin/bash
#Calls CreateSQLFile java class for each file in the tsv_streetfiles directory
#This generates a sql file of all tsv files in the directory
for file in /data/geoapi_data/street_finder/tsv_streetfiles/*; do
	java -cp ~/GeoApi/target/classes/ gov.nysenate.sage.scripts.StreetFinder.Scripts.CreateSQLFile "$file"
	echo $file added
done
echo SQL file created
