#!/bin/bash
#special conversion script for NYC street files
# -fixed 4 is a special trick that gets the files into a better txt format than normal
echo "Converting $1 to .txt"
pdftotext -fixed 4 /data/geoapi_data/street_finder/raw_streetfiles/$1
